export const ENV = {
    URL : "https://ventaslm.paginaslm.cl",
    API_URL: "https://spanel.cl/spanel/api/index.php?",
    ENDPOINTS: {
      LOGIN: "login",
      USERS_ME: "user",
      CSRFTOKEN : "createcsrf",
      COLABORADORES : "colaboradores",
      DESEMPENO : "desempeno",
      DESEMPENOEVALUACION : "desempenoevaluacion",
      DESEMPENOEVALUACIONSUB : "desempenoevaluacionsubcategoria",
      DESEMPENOCONDUCTA : "desempenoconducta",
      DESEMPENOPORCENTAJEOPTIMO : "desempenioporcentaje",
      DESEMEMPENOREGISTRAR : "registrarrevaluacion",
      PLANESSUPERVISION: "plansupervision",
      VERDESEMPENOVER: "verdesempenovergral",
      CHECKLIST : "checklist",
      CKECKLISTITEM : "checklistitem",
      CKECKLISTITEMCONTENIDO : "checklistitemcontenido",
      CKECKLISTAPLICAR : "checklistaplicar",
      MEJORAS : "mejoras",
      MEJORASFOTOS : "mejorasfotos",
      MEJORASPLAN : "mejorasplan",
      CAPACITACION : "capacitacion",
      CAPACITACIONIMP : "capacitacionimprimir",
      CAPACITACIONCONTENIDO : "capacitacioncontenido",
      CAPACITACIONASIGNAREVALUACION : "capacitacionasignarevaluacion",
      CAPACITACIONASIGNARPARTICIPANTE : "capacitacionasignarparticipante",
      
    },
    IMPRIMIR:"https://spanel.cl/spanel/api/imprimir/",
    STORAGE: {
      TOKEN: "tokenspanel",
    },
    URLAPP: "ventaslm.paginaslm.cl",
  };