const home = {
    root: "homeRoot",
    home: "home",
    colaboradores: "colaboradores",
    colaboradoresCrear: "colaboradores-crear",
    colaboradoresEditar: "colaboradores-editar",
    desempeno: "desempeno",
    desempenoCrear: "desempeno-crear",
    desempenoEditar: "desempeno-editar",
    desempenoEvaluacion: "desempenoEvaluacion",
    desempenoEvaluacionCrear: "desempenoEvaluacion-crear",
    desempenoEvaluacionEditar: "desempenoEvaluacion-editar",
    desempenoEvaluacionSub: "desempenoEvaluacionSub",
    desempenoEvaluacionSubCrear: "desempenoEvaluacionSub-crear",
    desempenoEvaluacionSubEditar: "desempenoEvaluacionSub-editar",
    desempenoEvaluacionConducta: "desempenoEvaluacionConducta",
    desempenoEvaluacionConductaCrear: "desempenoEvaluacionConducta-crear",
    desempenoEvaluacionConductaEditar: "desempenoEvaluacionConducta-editar",
    desempenoPorcentajeOptimo: "desempenoPorcentajeOptimo",
    desempenoRegistrarEvaluacion: "desempenoRegistrarEvaluacion",
    desempenoReporteIndividual: "desempenoReporteIndividual",
    desempenoReporteGeneral: "desempenoReporteGeneral",
    desempenoReporteCategoria: "desempenoReporteCategoria",
  };
  
  const homeplan = {
    root: "homeplanRoot",
    homeplan: "homeplan",
    plansupervision: "plansupervision",
    plansupervisionCrear: "plansupervision-crear",
    plansupervisionEditar: "plansupervision-editar",
    verdesempenovergral: "verdesempenovergral",
    checklist: "checklist",
    checklistCrear: "checklist-crear",
    checklistEditar: "checklist-editar",
    checklistitem: "checklistitem",
    checklistitemCrear: "checklistitem-crear",
    checklistitemEditar: "checklistitem-editar",
    checklistitemcontenido: "checklistitemcontenido",
    checklistitemcontenidoCrear: "checklistitemcontenido-crear",
    checklistitemcontenidoEditar: "checklistitemcontenido-editar",
    checklistaplicar: "checklistaplicar",
    checklistaplicarFechas: "checklistaplicar-fechas",
    checklistaplicarMostrar: "checklistaplicar-mostrar",
    mejoras: "mejoras",
    mejorasCrear: "mejoras-crear",
    mejorasEditar: "mejoras-editar",
    mejorasTomarfoto: "mejoras-tomarfoto",
    mejorasVerFotos: "mejoras-verfotos",
    mejorasPlanCrear: "mejorasplan-crear",
    mejorasPlanSeguimiento: "mejorasplan-seguimiento",
    mejorasPlanEditar: "mejorasplan-editar",
    capacitacion: "capacitacion",
    capacitacionCrear: "capacitacion-crear",
    capacitacionEditar: "capacitacion-editar",
    capacitacionContenido: "capacitacioncontenido",
    capacitacionContenidoCrear: "capacitacioncontenido-crear",
    capacitacionContenidoEditar: "capacitacioncontenido-editar",
    capacitacionAsignarEvaluacion: "capacitacionasignarevaluacion",
    capacitacionAsignarParticipante : "capacitacionasignarparticipante",
    
  }
    
  const account = {
    root: "accountRoot",
    account: "account",
  };
  
  export const screensName = {
    tab: "tabRoot",
    home,
    homeplan,
    account,
  };